//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T212_Updates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T212_Updates.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the API call.
        /// </summary>
        internal static string Error_ApiCallFailed {
            get {
                return ResourceManager.GetString("Error_ApiCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key is invalid or not set.
        /// </summary>
        internal static string Error_InvalidApiKey {
            get {
                return ResourceManager.GetString("Error_InvalidApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh frequency is invalid.
        /// </summary>
        internal static string Error_InvalidRefreshFrequency {
            get {
                return ResourceManager.GetString("Error_InvalidRefreshFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PIEs found for this API Key.
        /// </summary>
        internal static string Error_NoPiesFound {
            get {
                return ResourceManager.GetString("Error_NoPiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the UI.
        /// </summary>
        internal static string Error_UpdateDisplayFailed {
            get {
                return ResourceManager.GetString("Error_UpdateDisplayFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account/cash.
        /// </summary>
        internal static string GetAccountCashEndPoint {
            get {
                return ResourceManager.GetString("GetAccountCashEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account/info.
        /// </summary>
        internal static string GetAccountMetaDataEndpoint {
            get {
                return ResourceManager.GetString("GetAccountMetaDataEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orders.
        /// </summary>
        internal static string GetEquityOrderEndpoint {
            get {
                return ResourceManager.GetString("GetEquityOrderEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orders.
        /// </summary>
        internal static string GetEquityOrdersEndpoint {
            get {
                return ResourceManager.GetString("GetEquityOrdersEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata/exchanges.
        /// </summary>
        internal static string GetExchangesEndpoint {
            get {
                return ResourceManager.GetString("GetExchangesEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata/instruments.
        /// </summary>
        internal static string GetInstrumentsEndpoint {
            get {
                return ResourceManager.GetString("GetInstrumentsEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pies.
        /// </summary>
        internal static string GetPieEndpoint {
            get {
                return ResourceManager.GetString("GetPieEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pies.
        /// </summary>
        internal static string GetPiesEndpoint {
            get {
                return ResourceManager.GetString("GetPiesEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portfolio/ticker.
        /// </summary>
        internal static string GetPositionsByTickerEndpoint {
            get {
                return ResourceManager.GetString("GetPositionsByTickerEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portfolio.
        /// </summary>
        internal static string GetPositionsEndpoint {
            get {
                return ResourceManager.GetString("GetPositionsEndpoint", resourceCulture);
            }
        }
    }
}
